### ISSUE TITLE
Testing Lib Addition

### ISSUE THREAD

**Issue by SamKomesarook** [saucesteals/electron-typescript-react-tailwind-redux#13]
Would ya'll be open to adding a testing library to this boilerplate? Maybe [spectron](https://www.electronjs.org/spectron) and [mocha](https://mochajs.org/)?

I'd be happy to add those libs and put it up for review, as I am integrating them at the moment for a project.

**Comment by saucesteals** [comment]
> Would ya'll be open to adding a testing library to this boilerplate? Maybe [spectron](https://www.electronjs.org/spectron) and [jest](https://jestjs.io/)?
> 
> I'd be happy to add those libs and put it up for review, as I am integrating them at the moment for a project.

I actually have testing with ci implemented on a project using the boilerplate but was a little hesitant on adding it onto the boilerplate itself because it may just be a little "too much" given with just the boilerplate to whoever is using it.

I spoke to one of the main maintainers of Electron Userland (may be the creator if I'm not mistaken) at the time of starting the boilerplate and they brought up actually a really good point about the boilerplate having too much packed into it that then results in the developer that uses the boilerplate missing the entire learning process of how to setup and use everything thats there for them. 

Id say the boilerplate does definitely already have a lot more than it should and adding on a whole another big part (testing) may be unnecessary.

**Comment by SamKomesarook** [comment]
I understand the learning perspective, but I personally use boilerplates like this to speed up my dev process so that I can get right to functionality instead of wasting time installing and setting up packages.

I appreciate the quick response though, thanks :)
